project_id = "qzqomqctuqldexnxgmlh"

[functions.event-assistant]
verify_jwt = false

[functions.scrape-meetup]
verify_jwt = false

[functions.find-matches]
verify_jwt = false

[functions.send-dating-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.verify-social-profiles]
verify_jwt = false

[functions.send-profile-notification]
verify_jwt = false
